# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Burn After Reading
email:       ''
description: ''
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://krishsatya.github.io/' # The base hostname & protocol for your site
twitter:     ''
github:      ''
instagram:   ''
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

collections:
  tags:
    output: true
    permalink: /tag/:name/

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
